
spring:
  config:
    activate:
      on-profile: dev

  # JPA 설정 (dev: update로 데이터 유지)
  jpa:
    hibernate:
      ddl-auto: update  # 기존 테이블 업데이트
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # 데이터베이스 설정 ((Railway PostgreSQL)
  datasource:
    url: ${DEV_POSTGRESQL_URL:jdbc:postgresql://localhost:5432/defaultdb}  # Railway DB 엔드포인트로 변경
    username: ${DEV_POSTGRESQL_USERNAME:postgres}
    password: ${DEV_POSTGRESQL_PASSWORD:password}
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1200000

# Logging for debugging database connection
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.datasource: DEBUG

  # 카카오 로그인 설정 (Sandbox 앱 키 공유, provider는 common에서 상속)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${DEV_KAKAO_REST_API_KEY}
            client-secret: ${DEV_KAKAO_CLIENT_SECRET}
            redirect-uri: http://echobloom.co.kr/auth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

# JWT 설정
jwt:
  secret: ${DEV_JWT_SECRET}
  access-token-expiration-in-seconds: 3600
  refresh-token-expiration-in-seconds: 604800

# clova 설정
clova:
  api-key: ${DEV_CLOVA_API_KEY}

  # clova speech recognition 설정
  speech-recognition:
    client-id: ${DEV_CLOVA_CLIENT_ID}
    client-secret: ${DEV_CLOVA_CLIENT_SECRET}

# Swagger 설정(운영 환경에서는 비활성화)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false