
spring:
  config:
    activate:
      on-profile: common
  application:
    name: echo-bloom-server

  # H2 콘솔을 기본적으로 비활성화
  h2:
    console:
      enabled: false
    # JPA
  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      naming:
        physical-strategy: com.checkmate.bub.global.config.CamelCaseToSnakeAndUpperCaseStrategy

    # 추가: OAuth2 Resource Server 설정 (JWT issuer-uri – Kakao 토큰 검증)
  security:
    oauth2:
      resourceserver:
        jwt:
          dpop: false  // DPoP disable (문서 미지원 – 테스트 필요[2])