
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    # NCP Cloud DB for PostgreSQL의 연결 정보를 입력하세요.
    url: jdbc:postgresql://<YOUR_DB_HOST>:5432/<YOUR_DB_NAME>
    username: ${PROD_POSTGRESQL_USERNAME}
    password: ${PROD_POSTGRESQL_PASSWORD}

    # jpa 설정
  jpa:
    hibernate:
      # (매우 중요) 운영 환경에서는 절대로 JPA가 스키마를 건드리지 않도록 'none'으로 설정합니다.
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 운영 환경에서는 일반적으로 불필요한 SQL 로그를 남기지 않도록 설정합니다.
# common.yml의 설정을 덮어쓰고 싶다면 아래와 같이 명시적으로 레벨을 지정할 수 있습니다.
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info
