name: Deploy to NCP Server
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode SSH Key
        id: decode_key
        run: |
          RAW_KEY=$(echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d)
          echo "raw_key<<EOF" >> $GITHUB_OUTPUT
          echo "$RAW_KEY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ steps.decode_key.outputs.raw_key }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            # Kill all Java
