name: Deploy to NCP Server
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode SSH Key
        id: decode_key
        run: |
          RAW_KEY=$(echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d)
          echo "raw_key<<EOF" >> $GITHUB_OUTPUT  # Set as multi-line output
          echo "$RAW_KEY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ steps.decode_key.outputs.raw_key }}  # Pass decoded raw key
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            REPO_DIR="/root/echo-bloom-server"
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/checkmate-BUB/echo-bloom-server.git "$REPO_DIR"
            fi
            cd "$REPO_DIR"
            git pull origin main
            chmod +x ./gradlew
            ./gradlew clean build -x test
            pkill -9 -f "java -jar.*echo-bloom-server" || true
            sleep 2
            if pgrep -f "java -jar.*echo-bloom-server" > /dev/null; then
              echo "Failed to kill app" >&2
              exit 1
            fi
            nohup java -jar -Dspring.profiles.active=dev build/libs/echo-bloom-server-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            echo "Deployment completed"
