name: Deploy to NCP Server
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode SSH Key
        id: decode_key
        run: |
          RAW_KEY=$(echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d -i)  # -i: 무효 입력 무시 (오류 방지)
          echo "raw_key<<EOF" >> $GITHUB_OUTPUT
          echo "$RAW_KEY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ steps.decode_key.outputs.raw_key }}  # 디코딩된 키 사용 (key_path 대신 key로 변경)
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            # Kill all Java processes to prevent OOM
            pkill -9 -f 'java' || true
            sleep 2

            # Debug: List current Java processes (should be empty)
            ps aux | grep java || true

            # Verify no Java processes remain
            if pgrep -f 'java' > /dev/null; then
              echo "Failed to kill Java processes" >&2
              exit 1
            fi

            # Prepare directory
            REPO_DIR="/root/echo-bloom-server"
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/checkmate-BUB/echo-bloom-server.git "$REPO_DIR"
            fi
            cd "$REPO_DIR"
            git pull origin main
            chmod +x ./gradlew

            # Build with memory limits
            ./gradlew clean build -x test -Dorg.gradle.jvmargs="-Xmx1g" --no-daemon

            # Run app with memory limits
            nohup java -Xmx1g -Xms256m -jar -Dspring.profiles.active=dev build/libs/echo-bloom-server-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            # Verify only one Java process
            sleep 2
            JAVA_COUNT=$(pgrep -f 'java' | wc -l)
            if [ "$JAVA_COUNT" -ne 1 ]; then
              echo "Error: Expected 1 Java process, found $JAVA_COUNT" >&2
              exit 1
            fi

            # Debug: List running Java processes after deploy
            ps aux | grep java || true

            echo "Deployment completed"
